# Generated by Django 3.0.8 on 2021-02-26 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inst', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='institue',
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(max_length=10)),
                ('inst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance_system.Institute')),
            ],
        ),
        migrations.AddField(
            model_name='faculty',
            name='dept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance_system.Department'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='inst',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance_system.Institute'),
        ),
    ]
