# Generated by Django 3.0.8 on 2021-02-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_system', '0004_auto_20210226_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='reg_id',
            field=models.IntegerField(null=True),
        ),
    ]
