# Generated by Django 3.0.8 on 2021-03-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_system', '0011_auto_20210306_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='is_in_or_out',
            field=models.BooleanField(default=0),
        ),
    ]
