# Generated by Django 3.0.8 on 2021-03-07 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_system', '0013_auto_20210307_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='is_in_or_out',
        ),
    ]
