# Generated by Django 3.0.8 on 2021-03-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_system', '0016_trainingdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_status',
            field=models.BooleanField(default=False),
        ),
    ]
