# Generated by Django 3.0.8 on 2021-03-25 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_system', '0019_person_is_pass_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='is_pass_change',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
