# Generated by Django 3.0.8 on 2021-04-10 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_system', '0020_auto_20210325_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_leave',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='shift_leave',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='type_leave',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
